# Site settings
title: Onderwijs Innovatietraject Design Thinking 
subtitle: door Arteveldehogeschool Gent
email: info@arteveldehs.be
description: Projectwebsite OIT 2018 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stanseel.github.io/hcd" # the base hostname & protocol for your site
author:

# Social settings

# Sass building
sass:
    sass_dir: _sass
    
# Build settings
markdown: kramdown
